# RNN

In [1]:
import torch
import torch.nn as nn
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
from torch.utils.data import Dataset, DataLoader

In [295]:
df = pd.read_csv("/Users/animeshsingh/Desktop/Datasets/general_knowledge_qa.csv")
df.head()

,question,answer,question_type,image
0,How many days do we have in a week?,Seven,General Knowledge For Kids,NaN
1,How many days are there in a normal year?,365 (not a leap year),General Knowledge For Kids,NaN
2,How many colors are there in a rainbow?,7,General Knowledge For Kids,NaN
3,Which animal is known as the ‘Ship of the Dese...,Camel,General Knowledge For Kids,NaN
4,How many letters are there in the English alph...,26,General Knowledge For Kids,NaN

In [296]:
df = df.drop(columns = ['question_type', 'image'])
df.head()

                                            question                 answer
0                How many days do we have in a week?                  Seven
1          How many days are there in a normal year?  365 (not a leap year)
2            How many colors are there in a rainbow?                      7
3  Which animal is known as the ‘Ship of the Dese...                  Camel
4  How many letters are there in the English alph...                     26

In [297]:
df.shape

(930, 2)

In [298]:
unique_q = []
unique_a = []

def tokenize(text):
    text = text.replace('?', ' ')
    text = text.replace("'", ' ')
    text = text.replace('(', ' ')
    text = text.replace(')', ' ')
    text = text.lower()
    return text.split()

for sent in df['question']:
    sent = tokenize(sent)
    unique_q.append(sent)

for sent in df['answer']:
    sent = tokenize(sent)
    unique_a.append(sent)

In [299]:
vocab = {'<UNK>' : 0}

In [300]:
type(unique_q)

list

In [301]:
unique_q = [item for lst in unique_q for item in lst]
unique_a = [item for lst in unique_a for item in lst]

In [302]:
len(unique_q), len(unique_a)

(7508, 1632)

In [303]:
unique_q = set(unique_q)
unique_a = set(unique_a)

In [304]:
len(unique_q), len(unique_a)

(1699, 937)

In [305]:
unique_q = list(unique_q)
unique_a = list(unique_a)

In [306]:
vocab = unique_q + unique_a

In [307]:
len(vocab)

2636

In [308]:
vocab = list(set(vocab))

In [309]:
len(vocab)

2309

In [310]:
type(vocab)

list

In [311]:
vocabulary = {'<PAD>' : 0, '<UNK>' : 1, '<SOS>' : 2, '<EOS>' : 3}

In [312]:
tokens = [i for i in range(len(vocabulary), len(vocab) + 1)]

In [313]:
deect = dict(zip(vocab, tokens))

In [314]:
deect

{'asking': 4,
 'sun': 5,
 'saarc': 6,
 'norway': 7,
 'stars': 8,
 'into': 9,
 'none': 10,
 'founder': 11,
 'archimedes': 12,
 'people.': 13,
 'strings': 14,
 'full': 15,
 '916': 16,
 'will': 17,
 'reappointed': 18,
 'bay': 19,
 '27*0': 20,
 'edison': 21,
 'rbi': 22,
 'cow': 23,
 'lies': 24,
 'was': 25,
 'plant': 26,
 'year.': 27,
 'buddhist': 28,
 'berners-lee': 29,
 'beehives': 30,
 'thousand': 31,
 'nuclear': 32,
 'common': 33,
 'tedros': 34,
 'history': 35,
 'carry': 36,
 'a.': 37,
 'mango': 38,
 'letters': 39,
 'vowels': 40,
 'kalaam,': 41,
 'baku': 42,
 'cross': 43,
 'land': 44,
 'hat-trick': 45,
 'york': 46,
 'mother,': 47,
 'robot': 48,
 'x-rays': 49,
 'ella': 50,
 'frescos': 51,
 '2': 52,
 'treats': 53,
 'beri-beri': 54,
 'eraser,': 55,
 'a': 56,
 'read-only': 57,
 '____________.': 58,
 'environment': 59,
 'ryder': 60,
 'malic': 61,
 'atmosphere': 62,
 'council': 63,
 'thomas': 64,
 'plants': 65,
 'nirvana': 66,
 'sometimes': 67,
 'sky': 68,
 'distance': 69,
 'eggs': 70,
 'am': 71,
 'philadelphia': 72,
 'titan': 73,
 'food': 74,
 'its': 75,
 'sports': 76,
 'players': 77,
 'pigeon,': 78,
 'boat': 79,
 'twin': 80,
 'violet,': 81,
 'cephalopod': 82,
 'absorbed': 83,
 'fox': 84,
 'bank': 85,
 'position': 86,
 'and': 87,
 '______.': 88,
 'euclid': 89,
 'standard': 90,
 'similar': 91,
 'years.': 92,
 'ink': 93,
 'country': 94,
 'reduced': 95,
 'lines': 96,
 '3,00,000': 97,
 'paulo': 98,
 '‘ramayana’': 99,
 'union': 100,
 'national': 101,
 'harvest': 102,
 'humanoid': 103,
 'soda': 104,
 'gases': 105,
 'forest': 106,
 'kingdom': 107,
 'ozone': 108,
 'sharks': 109,
 'of': 110,
 'calcium': 111,
 'rom': 112,
 'gautama': 113,
 'english': 114,
 'author': 115,
 'location': 116,
 'guards': 117,
 'teacher': 118,
 'cat': 119,
 'barrier': 120,
 'baird': 121,
 'victor': 122,
 'cyber': 123,
 'prix': 124,
 'court': 125,
 'popular': 126,
 'zeroes': 127,
 'give': 128,
 'horses': 129,
 'red,': 130,
 'ekta': 131,
 'ganymede': 132,
 's': 133,
 'opium': 134,
 'please': 135,
 'during': 136,
 'chopra': 137,
 'supply': 138,
 'invests': 139,
 'pencil,': 140,
 '2020.': 141,
 'tree': 142,
 'dioxide': 143,
 'revolve': 144,
 'donor”': 145,
 '“gift': 146,
 'hypochlorite,': 147,
 'phycology': 148,
 'sound': 149,
 'azerbaijan': 150,
 'prime': 151,
 'k': 152,
 'water': 153,
 'hen': 154,
 'vitamin”': 155,
 'mt.': 156,
 'made': 157,
 'coco': 158,
 '21': 159,
 'turkey': 160,
 'get': 161,
 'times': 162,
 'tropical': 163,
 'warming': 164,
 'painted': 165,
 'anniversary': 166,
 'cups': 167,
 'fire': 168,
 'metal': 169,
 'colours': 170,
 'yamuna': 171,
 'composed': 172,
 'buddha': 173,
 'most': 174,
 'award': 175,
 'place': 176,
 'stomata': 177,
 'coconut': 178,
 'own': 179,
 'air': 180,
 'geometry”': 181,
 'rights': 182,
 'belt': 183,
 'introduced': 184,
 'mataram': 185,
 'process': 186,
 'taste': 187,
 'wool': 188,
 'pataliputra': 189,
 'sikh': 190,
 'number': 191,
 'vikram': 192,
 'guglielmo': 193,
 'christopher': 194,
 'raman': 195,
 'human': 196,
 'iron': 197,
 'paris,': 198,
 'diwali': 199,
 'when': 200,
 'developed': 201,
 'scientist': 202,
 'p': 203,
 'lives': 204,
 'hosted': 205,
 'vacuum': 206,
 'awarded': 207,
 'seas': 208,
 'sardar': 209,
 'manipur': 210,
 'earthquakes': 211,
 'lala': 212,
 'ophidiophobia': 213,
 'among': 214,
 'j.k.': 215,
 'obtained': 216,
 '1914': 217,
 'country”': 218,
 'kidneys': 219,
 'goat': 220,
 'hexagon': 221,
 'baer': 222,
 'positioning': 223,
 'wonderland,': 224,
 'zones': 225,
 'reserve': 226,
 'lionel': 227,
 'lacrosse/ice': 228,
 'helium': 229,
 '‘class’': 230,
 'may': 231,
 'commonly': 232,
 'bhagat': 233,
 'sistine': 234,
 'pound': 235,
 'caesar”': 236,
 'ruble': 237,
 'sterling': 238,
 'calculate': 239,
 'august': 240,
 'armstrong': 241,
 'develop': 242,
 'meteorology': 243,
 'approximate': 244,
 'begin': 245,
 'kitten': 246,
 'platelets': 247,
 'isro': 248,
 'hummingbird': 249,
 'thiruvananthapuram': 250,
 'christmas': 251,
 '1903': 252,
 'cinderella': 253,
 'ship': 254,
 '__________': 255,
 'aladdin': 256,
 'carle': 257,
 'kohli': 258,
 'saina': 259,
 'soil': 260,
 'polo': 261,
 'memory': 262,
 'indicates': 263,
 'states': 264,
 'decade': 265,
 'bowl’': 266,
 'carp': 267,
 'golf': 268,
 'years': 269,
 'eats': 270,
 'library': 271,
 'non-metal': 272,
 'brown': 273,
 'fe': 274,
 '_________': 275,
 'fight': 276,
 'mamba': 277,
 '5.75': 278,
 '1914-1918': 279,
 'footballer': 280,
 'march,': 281,
 'kanishka': 282,
 'specialist.': 283,
 'c.s.': 284,
 'mbbs': 285,
 'italy': 286,
 'calendar': 287,
 'jupiter,': 288,
 '22/7': 289,
 'launch': 290,
 'astronaut': 291,
 'moons.': 292,
 'produced': 293,
 'stadium': 294,
 'dennis': 295,
 'mars': 296,
 'bill': 297,
 '______________': 298,
 'carroll': 299,
 'fourth': 300,
 'giraffe': 301,
 'theory': 302,
 'mother': 303,
 'same': 304,
 'building,': 305,
 'franklin': 306,
 '3600': 307,
 'milkha': 308,
 'lightest': 309,
 'locate': 310,
 '26': 311,
 'gates': 312,
 'lamp': 313,
 'copper': 314,
 'islands': 315,
 'dove': 316,
 'rowland': 317,
 'walk': 318,
 'colt': 319,
 'abundant': 320,
 'rain': 321,
 'bahrain': 322,
 'o,': 323,
 'stick': 324,
 'manuel': 325,
 'charminar': 326,
 'deadly': 327,
 '2011': 328,
 'leaning': 329,
 'delhi': 330,
 'organs': 331,
 'bangladesh': 332,
 'dinosaur,': 333,
 'congo': 334,
 '10+4': 335,
 'introduce': 336,
 '“little': 337,
 'equals': 338,
 'spokes': 339,
 'life': 340,
 'complete': 341,
 'brain.': 342,
 'james': 343,
 '–': 344,
 'born': 345,
 'tuesday': 346,
 'up': 347,
 '48': 348,
 'computer.': 349,
 'brain’s': 350,
 'need': 351,
 'patel': 352,
 '“charlie': 353,
 'the': 354,
 'hypertext': 355,
 'once': 356,
 'wheel': 357,
 'fingernail': 358,
 'nitrogen': 359,
 'continue': 360,
 'bachelor': 361,
 'ship,': 362,
 'eruption': 363,
 'autumn': 364,
 'leaf': 365,
 'throw': 366,
 'copenhagen': 367,
 'east': 368,
 'sky”': 369,
 'nutrients': 370,
 'placed': 371,
 'care!': 372,
 'four-digit': 373,
 'orient': 374,
 'bear': 375,
 'letter': 376,
 'hammer': 377,
 'onam': 378,
 'angkor': 379,
 'meridiem': 380,
 'biwa': 381,
 'spratly': 382,
 'weight': 383,
 'that': 384,
 '___': 385,
 'monument': 386,
 'vehicle': 387,
 'sahara': 388,
 'newton,': 389,
 '3': 390,
 'hour': 391,
 'highest': 392,
 'tibet': 393,
 'resulting': 394,
 'kangaroo': 395,
 'who': 396,
 'atlantic': 397,
 'five': 398,
 'base': 399,
 'language': 400,
 'caddie': 401,
 'cup': 402,
 'blink': 403,
 'nehru': 404,
 'organization,': 405,
 'persian': 406,
 'china': 407,
 'acute': 408,
 'geometric': 409,
 'world': 410,
 'nobel': 411,
 'equal': 412,
 'drama': 413,
 '1.618': 414,
 'access': 415,
 'source': 416,
 'owned': 417,
 '‘wings': 418,
 'parts': 419,
 'non-quadrilateral': 420,
 'everest': 421,
 'ratna': 422,
 'identity': 423,
 'exosphere,': 424,
 'road': 425,
 'africa': 426,
 'program': 427,
 'cow,': 428,
 'apj': 429,
 'thailand': 430,
 'back': 431,
 'wireless': 432,
 'fought': 433,
 'mosquitoes': 434,
 'kanchenjunga': 435,
 'excess': 436,
 'goitre': 437,
 'freshwater': 438,
 'space': 439,
 'clothes': 440,
 'early': 441,
 'sheep': 442,
 'ghebreyesus': 443,
 'supercomputer': 444,
 'v.': 445,
 'ram': 446,
 'children’s': 447,
 'hippocrates': 448,
 'atomic': 449,
 'people': 450,
 'biggest': 451,
 'child': 452,
 'capital': 453,
 'over': 454,
 'sleep': 455,
 'honeybees': 456,
 'processing': 457,
 'oscar': 458,
 'name': 459,
 'mice': 460,
 'hydrochloric': 461,
 'week': 462,
 '“grand': 463,
 'hydrogen': 464,
 'random': 465,
 'teaches': 466,
 'world,': 467,
 'mathematics”': 468,
 'microsoft': 469,
 'necessary': 470,
 'j': 471,
 'connected': 472,
 'powell': 473,
 'countries': 474,
 'bones.': 475,
 'a.p.j.': 476,
 'discover': 477,
 'backward': 478,
 '“oak': 479,
 'gravity': 480,
 'dr': 481,
 'turns': 482,
 '1': 483,
 'state': 484,
 'diamond': 485,
 'super': 486,
 '“blue': 487,
 'last': 488,
 'some': 489,
 'related': 490,
 'desert”': 491,
 'pack': 492,
 'sir': 493,
 'painter': 494,
 'tungsten': 495,
 '_____.': 496,
 'indicate': 497,
 '90˚': 498,
 '1985': 499,
 'home': 500,
 'producer': 501,
 'nath': 502,
 'summer': 503,
 'geoffrey': 504,
 'bohag': 505,
 'throat,': 506,
 'where': 507,
 'adiga': 508,
 'milky': 509,
 'slowest': 510,
 'african': 511,
 'hill': 512,
 'you': 513,
 'brazilian': 514,
 'origami': 515,
 'spain': 516,
 'dandi': 517,
 'types': 518,
 'uae': 519,
 'concept': 520,
 'your': 521,
 '0': 522,
 'ivory': 523,
 'conducts': 524,
 'nyctophobia': 525,
 'directions': 526,
 'neil': 527,
 'vegetables': 528,
 'ground': 529,
 'pisa': 530,
 'adam': 531,
 'located': 532,
 'logie': 533,
 'car': 534,
 '2020': 535,
 'look': 536,
 'pentagon': 537,
 'bulb': 538,
 'call': 539,
 'buttons.': 540,
 'video': 541,
 'atmosphere.': 542,
 'this': 543,
 'helm': 544,
 'indira': 545,
 'wednesday': 546,
 'inventor,': 547,
 'equator': 548,
 'her': 549,
 'modern': 550,
 'bharat': 551,
 '&': 552,
 'planet”': 553,
 '27': 554,
 'eye': 555,
 '50': 556,
 'layer': 557,
 'ii': 558,
 'rises': 559,
 'has': 560,
 '9999': 561,
 'goes': 562,
 'crosses': 563,
 'provider,': 564,
 'ratio': 565,
 'long': 566,
 '1930': 567,
 'desert': 568,
 'garden': 569,
 'chemical': 570,
 'articles': 571,
 'tokyo': 572,
 'called': 573,
 'corners': 574,
 'magic': 575,
 'traffic': 576,
 'system': 577,
 'visvesaraya': 578,
 'mercury': 579,
 'side': 580,
 'brightest': 581,
 'tale': 582,
 'plath': 583,
 'chlorophyll': 584,
 'healthy': 585,
 'yerevan': 586,
 'p.j.': 587,
 'winner': 588,
 'young': 589,
 'oxygen': 590,
 'coffee': 591,
 'world.': 592,
 'head': 593,
 'furniture': 594,
 '34': 595,
 'at': 596,
 'sunburn.': 597,
 'april': 598,
 'book—jungle': 599,
 'manatees': 600,
 'patna,': 601,
 'lots': 602,
 'sky.': 603,
 'b,': 604,
 'buddhists': 605,
 'usa': 606,
 'what': 607,
 'like': 608,
 'submerged': 609,
 'using': 610,
 'flow': 611,
 'banks': 612,
 'yellow,': 613,
 'sachin': 614,
 'km/sec': 615,
 'layers': 616,
 'game,': 617,
 'alva': 618,
 'raman,': 619,
 'equal.': 620,
 'series': 621,
 'powder': 622,
 'mario': 623,
 'einstein': 624,
 'after': 625,
 'sets': 626,
 'little': 627,
 'eyes': 628,
 'nehwal': 629,
 'punjab': 630,
 'gautham': 631,
 'we': 632,
 'dice': 633,
 'kipling': 634,
 'argentina': 635,
 'island': 636,
 'giza': 637,
 'china,': 638,
 '_______.': 639,
 '1884': 640,
 'rudyard': 641,
 'international': 642,
 'fire.': 643,
 '1896': 644,
 'teeth': 645,
 'tea': 646,
 'north': 647,
 'pigment': 648,
 'american': 649,
 'taj': 650,
 'grow': 651,
 'stay': 652,
 'brother,': 653,
 'story': 654,
 'toes.': 655,
 'orville': 656,
 'citric': 657,
 'orange,': 658,
 'wilhelm': 659,
 'bear’': 660,
 '2,': 661,
 'no': 662,
 'roots': 663,
 'divas': 664,
 'computer”': 665,
 'slam”': 666,
 'infinite': 667,
 'stripes’': 668,
 'color': 669,
 'nile”': 670,
 'dozen': 671,
 '______': 672,
 '“sorrow': 673,
 'cannot': 674,
 'emirates': 675,
 'surface': 676,
 'board': 677,
 'century': 678,
 'flowers’': 679,
 'resource': 680,
 'violin': 681,
 '“kitchen': 682,
 'invented': 683,
 'arthur': 684,
 'coelho': 685,
 'elephants”': 686,
 'fear': 687,
 'city”': 688,
 'president': 689,
 'games': 690,
 '“wait”': 691,
 'mesosphere,': 692,
 'infamous': 693,
 'ore': 694,
 'cricketer': 695,
 '6': 696,
 '16': 697,
 'virat': 698,
 'sight': 699,
 'blind.': 700,
 'zoo': 701,
 '“red': 702,
 'scotland': 703,
 'vegetable': 704,
 'july,': 705,
 '‘discovery': 706,
 'music': 707,
 'why': 708,
 'restoration': 709,
 'natural': 710,
 'mark': 711,
 'much': 712,
 'lord': 713,
 '‘great': 714,
 'ritchie': 715,
 'leonardo': 716,
 'd.12': 717,
 '2019': 718,
 'benjamin': 719,
 'relativity': 720,
 'roger': 721,
 'galaxy': 722,
 'china”': 723,
 'galaxies': 724,
 'protons': 725,
 'map': 726,
 'relate': 727,
 'four': 728,
 'moscow': 729,
 'surgeon,': 730,
 'morocco': 731,
 'dentist': 732,
 'kept': 733,
 'bolivia': 734,
 'data': 735,
 'belgium': 736,
 'frogs': 737,
 'chocolate': 738,
 'india”': 739,
 'jesus': 740,
 'prickle': 741,
 'raindrop': 742,
 'julian': 743,
 'peru': 744,
 'wags': 745,
 'lima': 746,
 'how': 747,
 'postage': 748,
 'asian': 749,
 'held': 750,
 'market': 751,
 'money': 752,
 'dog,': 753,
 'sharma': 754,
 'present': 755,
 'lengths': 756,
 '12': 757,
 'opposite': 758,
 'medicine': 759,
 'bhai': 760,
 'europe': 761,
 'wilbur': 762,
 'women': 763,
 'igloo': 764,
 'days': 765,
 'pratyush': 766,
 'usain': 767,
 'sty': 768,
 'charles': 769,
 '“indian': 770,
 '33': 771,
 'algae': 772,
 'turn': 773,
 'car,': 774,
 'olympics': 775,
 'whale': 776,
 'troposphere': 777,
 'vijayalaya': 778,
 'extinct': 779,
 'another': 780,
 'true': 781,
 '________________': 782,
 '29': 783,
 'chaucer': 784,
 'butterfly': 785,
 'do': 786,
 'rashtriya': 787,
 'elephant,': 788,
 'brics,': 789,
 '9': 790,
 'sphygmomanometer': 791,
 'homi': 792,
 'blair': 793,
 'modi': 794,
 'only': 795,
 'maximum': 796,
 'got': 797,
 'deposit': 798,
 'cooks': 799,
 'age': 800,
 'karmakar': 801,
 'bhat': 802,
 'subscriber': 803,
 'tim': 804,
 'vyommitra': 805,
 'wrote': 806,
 'asia': 807,
 'nile': 808,
 'very': 809,
 'mountain': 810,
 'layers.': 811,
 'olympic': 812,
 'measure': 813,
 'life,': 814,
 'orbit': 815,
 'gypsum': 816,
 '4': 817,
 'john': 818,
 'through': 819,
 'colors': 820,
 'in': 821,
 'reputed': 822,
 'north,': 823,
 'fly': 824,
 'humps.': 825,
 'wisdom': 826,
 'two': 827,
 'chess,': 828,
 'drives': 829,
 'suess': 830,
 '5th': 831,
 'arundhati': 832,
 'whom': 833,
 'create': 834,
 '“god': 835,
 'joey': 836,
 'going': 837,
 'potato,': 838,
 'their': 839,
 'even': 840,
 'india.': 841,
 'pen': 842,
 'brother': 843,
 '24': 844,
 'wings': 845,
 'established': 846,
 'maternal': 847,
 'fundamental': 848,
 'statue': 849,
 'devi': 850,
 'top': 851,
 'january,': 852,
 'football': 853,
 'seasons': 854,
 'asia,': 855,
 '5': 856,
 'neeraj': 857,
 'mickey': 858,
 'brazil': 859,
 'prasad': 860,
 'small': 861,
 'sea': 862,
 'woollen': 863,
 '“financial': 864,
 'e,': 865,
 'wrist': 866,
 'rai': 867,
 'ganga': 868,
 'electricity': 869,
 'steam': 870,
 'belly': 871,
 '’': 872,
 'coldest': 873,
 'louvre': 874,
 'sonar': 875,
 'whales': 876,
 'beautiful': 877,
 'carpenter,': 878,
 'season': 879,
 'uranus': 880,
 'calcutta': 881,
 'product': 882,
 'seconds': 883,
 'named': 884,
 'planet,': 885,
 'known': 886,
 'square': 887,
 'hearts.': 888,
 'won': 889,
 'start': 890,
 'economics': 891,
 '‘festival': 892,
 'did': 893,
 'assam': 894,
 'wound': 895,
 'cells': 896,
 'cartoon': 897,
 'comes': 898,
 'potato': 899,
 'novelist': 900,
 'helps': 901,
 'calf': 902,
 'hockey': 903,
 'patients': 904,
 'use': 905,
 'bonaparte': 906,
 'wheels': 907,
 'global': 908,
 'tereshkova': 909,
 'winter': 910,
 '144': 911,
 'which': 912,
 'lights': 913,
 '1939-1945': 914,
 'november': 915,
 'telephone': 916,
 'homoeopathy': 917,
 'girl': 918,
 'any': 919,
 'wwi': 920,
 'nitrous': 921,
 '‘panchathantra’': 922,
 '1908': 923,
 'marconi': 924,
 'breathe': 925,
 'anopheles': 926,
 'dubai,': 927,
 'watt': 928,
 'thief': 929,
 'mahatma': 930,
 'messi': 931,
 'shapes': 932,
 'ginger': 933,
 'lexicographer': 934,
 'grandfather': 935,
 '‘fruit': 936,
 'line': 937,
 'pressure': 938,
 'temperature': 939,
 'authored': 940,
 'moisture': 941,
 'glucose': 942,
 'solar': 943,
 'sperm': 944,
 'arachnophobia': 945,
 'badminton': 946,
 'below': 947,
 'neptune': 948,
 'health': 949,
 'kennel': 950,
 '999': 951,
 'owl': 952,
 'largest': 953,
 'george': 954,
 'columbus': 955,
 'somniferum': 956,
 'valentina': 957,
 'holes': 958,
 'strange': 959,
 'situated': 960,
 'chatterjee': 961,
 'narnia”': 962,
 'belong': 963,
 'potter': 964,
 'gold': 965,
 'bang': 966,
 'sum': 967,
 'ascorbic': 968,
 'post': 969,
 'table': 970,
 'belongs': 971,
 'rupee': 972,
 'colour': 973,
 'pacific': 974,
 'lewis': 975,
 'hours': 976,
 'three-digit': 977,
 'may,': 978,
 'terms’': 979,
 'tower': 980,
 'laika,': 981,
 'backwards': 982,
 'countries,': 983,
 'they': 984,
 'day': 985,
 'bat,': 986,
 'sylvia': 987,
 'care': 988,
 'millimeters': 989,
 'dynasty': 990,
 'have': 991,
 'ten': 992,
 'satellite': 993,
 'triangle': 994,
 'telescope': 995,
 'penicillin': 996,
 'angles': 997,
 '82': 998,
 '14th': 999,
 'aurora': 1000,
 'camels': 1001,
 'time': 1002,
 'freezes': 1003,
 ...}

In [315]:
vocabulary = vocabulary | deect

In [316]:
vocabulary

{'<PAD>': 0,
 '<UNK>': 1,
 '<SOS>': 2,
 '<EOS>': 3,
 'asking': 4,
 'sun': 5,
 'saarc': 6,
 'norway': 7,
 'stars': 8,
 'into': 9,
 'none': 10,
 'founder': 11,
 'archimedes': 12,
 'people.': 13,
 'strings': 14,
 'full': 15,
 '916': 16,
 'will': 17,
 'reappointed': 18,
 'bay': 19,
 '27*0': 20,
 'edison': 21,
 'rbi': 22,
 'cow': 23,
 'lies': 24,
 'was': 25,
 'plant': 26,
 'year.': 27,
 'buddhist': 28,
 'berners-lee': 29,
 'beehives': 30,
 'thousand': 31,
 'nuclear': 32,
 'common': 33,
 'tedros': 34,
 'history': 35,
 'carry': 36,
 'a.': 37,
 'mango': 38,
 'letters': 39,
 'vowels': 40,
 'kalaam,': 41,
 'baku': 42,
 'cross': 43,
 'land': 44,
 'hat-trick': 45,
 'york': 46,
 'mother,': 47,
 'robot': 48,
 'x-rays': 49,
 'ella': 50,
 'frescos': 51,
 '2': 52,
 'treats': 53,
 'beri-beri': 54,
 'eraser,': 55,
 'a': 56,
 'read-only': 57,
 '____________.': 58,
 'environment': 59,
 'ryder': 60,
 'malic': 61,
 'atmosphere': 62,
 'council': 63,
 'thomas': 64,
 'plants': 65,
 'nirvana': 66,
 'sometimes': 67,
 'sky': 68,
 'distance': 69,
 'eggs': 70,
 'am': 71,
 'philadelphia': 72,
 'titan': 73,
 'food': 74,
 'its': 75,
 'sports': 76,
 'players': 77,
 'pigeon,': 78,
 'boat': 79,
 'twin': 80,
 'violet,': 81,
 'cephalopod': 82,
 'absorbed': 83,
 'fox': 84,
 'bank': 85,
 'position': 86,
 'and': 87,
 '______.': 88,
 'euclid': 89,
 'standard': 90,
 'similar': 91,
 'years.': 92,
 'ink': 93,
 'country': 94,
 'reduced': 95,
 'lines': 96,
 '3,00,000': 97,
 'paulo': 98,
 '‘ramayana’': 99,
 'union': 100,
 'national': 101,
 'harvest': 102,
 'humanoid': 103,
 'soda': 104,
 'gases': 105,
 'forest': 106,
 'kingdom': 107,
 'ozone': 108,
 'sharks': 109,
 'of': 110,
 'calcium': 111,
 'rom': 112,
 'gautama': 113,
 'english': 114,
 'author': 115,
 'location': 116,
 'guards': 117,
 'teacher': 118,
 'cat': 119,
 'barrier': 120,
 'baird': 121,
 'victor': 122,
 'cyber': 123,
 'prix': 124,
 'court': 125,
 'popular': 126,
 'zeroes': 127,
 'give': 128,
 'horses': 129,
 'red,': 130,
 'ekta': 131,
 'ganymede': 132,
 's': 133,
 'opium': 134,
 'please': 135,
 'during': 136,
 'chopra': 137,
 'supply': 138,
 'invests': 139,
 'pencil,': 140,
 '2020.': 141,
 'tree': 142,
 'dioxide': 143,
 'revolve': 144,
 'donor”': 145,
 '“gift': 146,
 'hypochlorite,': 147,
 'phycology': 148,
 'sound': 149,
 'azerbaijan': 150,
 'prime': 151,
 'k': 152,
 'water': 153,
 'hen': 154,
 'vitamin”': 155,
 'mt.': 156,
 'made': 157,
 'coco': 158,
 '21': 159,
 'turkey': 160,
 'get': 161,
 'times': 162,
 'tropical': 163,
 'warming': 164,
 'painted': 165,
 'anniversary': 166,
 'cups': 167,
 'fire': 168,
 'metal': 169,
 'colours': 170,
 'yamuna': 171,
 'composed': 172,
 'buddha': 173,
 'most': 174,
 'award': 175,
 'place': 176,
 'stomata': 177,
 'coconut': 178,
 'own': 179,
 'air': 180,
 'geometry”': 181,
 'rights': 182,
 'belt': 183,
 'introduced': 184,
 'mataram': 185,
 'process': 186,
 'taste': 187,
 'wool': 188,
 'pataliputra': 189,
 'sikh': 190,
 'number': 191,
 'vikram': 192,
 'guglielmo': 193,
 'christopher': 194,
 'raman': 195,
 'human': 196,
 'iron': 197,
 'paris,': 198,
 'diwali': 199,
 'when': 200,
 'developed': 201,
 'scientist': 202,
 'p': 203,
 'lives': 204,
 'hosted': 205,
 'vacuum': 206,
 'awarded': 207,
 'seas': 208,
 'sardar': 209,
 'manipur': 210,
 'earthquakes': 211,
 'lala': 212,
 'ophidiophobia': 213,
 'among': 214,
 'j.k.': 215,
 'obtained': 216,
 '1914': 217,
 'country”': 218,
 'kidneys': 219,
 'goat': 220,
 'hexagon': 221,
 'baer': 222,
 'positioning': 223,
 'wonderland,': 224,
 'zones': 225,
 'reserve': 226,
 'lionel': 227,
 'lacrosse/ice': 228,
 'helium': 229,
 '‘class’': 230,
 'may': 231,
 'commonly': 232,
 'bhagat': 233,
 'sistine': 234,
 'pound': 235,
 'caesar”': 236,
 'ruble': 237,
 'sterling': 238,
 'calculate': 239,
 'august': 240,
 'armstrong': 241,
 'develop': 242,
 'meteorology': 243,
 'approximate': 244,
 'begin': 245,
 'kitten': 246,
 'platelets': 247,
 'isro': 248,
 'hummingbird': 249,
 'thiruvananthapuram': 250,
 'christmas': 251,
 '1903': 252,
 'cinderella': 253,
 'ship': 254,
 '__________': 255,
 'aladdin': 256,
 'carle': 257,
 'kohli': 258,
 'saina': 259,
 'soil': 260,
 'polo': 261,
 'memory': 262,
 'indicates': 263,
 'states': 264,
 'decade': 265,
 'bowl’': 266,
 'carp': 267,
 'golf': 268,
 'years': 269,
 'eats': 270,
 'library': 271,
 'non-metal': 272,
 'brown': 273,
 'fe': 274,
 '_________': 275,
 'fight': 276,
 'mamba': 277,
 '5.75': 278,
 '1914-1918': 279,
 'footballer': 280,
 'march,': 281,
 'kanishka': 282,
 'specialist.': 283,
 'c.s.': 284,
 'mbbs': 285,
 'italy': 286,
 'calendar': 287,
 'jupiter,': 288,
 '22/7': 289,
 'launch': 290,
 'astronaut': 291,
 'moons.': 292,
 'produced': 293,
 'stadium': 294,
 'dennis': 295,
 'mars': 296,
 'bill': 297,
 '______________': 298,
 'carroll': 299,
 'fourth': 300,
 'giraffe': 301,
 'theory': 302,
 'mother': 303,
 'same': 304,
 'building,': 305,
 'franklin': 306,
 '3600': 307,
 'milkha': 308,
 'lightest': 309,
 'locate': 310,
 '26': 311,
 'gates': 312,
 'lamp': 313,
 'copper': 314,
 'islands': 315,
 'dove': 316,
 'rowland': 317,
 'walk': 318,
 'colt': 319,
 'abundant': 320,
 'rain': 321,
 'bahrain': 322,
 'o,': 323,
 'stick': 324,
 'manuel': 325,
 'charminar': 326,
 'deadly': 327,
 '2011': 328,
 'leaning': 329,
 'delhi': 330,
 'organs': 331,
 'bangladesh': 332,
 'dinosaur,': 333,
 'congo': 334,
 '10+4': 335,
 'introduce': 336,
 '“little': 337,
 'equals': 338,
 'spokes': 339,
 'life': 340,
 'complete': 341,
 'brain.': 342,
 'james': 343,
 '–': 344,
 'born': 345,
 'tuesday': 346,
 'up': 347,
 '48': 348,
 'computer.': 349,
 'brain’s': 350,
 'need': 351,
 'patel': 352,
 '“charlie': 353,
 'the': 354,
 'hypertext': 355,
 'once': 356,
 'wheel': 357,
 'fingernail': 358,
 'nitrogen': 359,
 'continue': 360,
 'bachelor': 361,
 'ship,': 362,
 'eruption': 363,
 'autumn': 364,
 'leaf': 365,
 'throw': 366,
 'copenhagen': 367,
 'east': 368,
 'sky”': 369,
 'nutrients': 370,
 'placed': 371,
 'care!': 372,
 'four-digit': 373,
 'orient': 374,
 'bear': 375,
 'letter': 376,
 'hammer': 377,
 'onam': 378,
 'angkor': 379,
 'meridiem': 380,
 'biwa': 381,
 'spratly': 382,
 'weight': 383,
 'that': 384,
 '___': 385,
 'monument': 386,
 'vehicle': 387,
 'sahara': 388,
 'newton,': 389,
 '3': 390,
 'hour': 391,
 'highest': 392,
 'tibet': 393,
 'resulting': 394,
 'kangaroo': 395,
 'who': 396,
 'atlantic': 397,
 'five': 398,
 'base': 399,
 'language': 400,
 'caddie': 401,
 'cup': 402,
 'blink': 403,
 'nehru': 404,
 'organization,': 405,
 'persian': 406,
 'china': 407,
 'acute': 408,
 'geometric': 409,
 'world': 410,
 'nobel': 411,
 'equal': 412,
 'drama': 413,
 '1.618': 414,
 'access': 415,
 'source': 416,
 'owned': 417,
 '‘wings': 418,
 'parts': 419,
 'non-quadrilateral': 420,
 'everest': 421,
 'ratna': 422,
 'identity': 423,
 'exosphere,': 424,
 'road': 425,
 'africa': 426,
 'program': 427,
 'cow,': 428,
 'apj': 429,
 'thailand': 430,
 'back': 431,
 'wireless': 432,
 'fought': 433,
 'mosquitoes': 434,
 'kanchenjunga': 435,
 'excess': 436,
 'goitre': 437,
 'freshwater': 438,
 'space': 439,
 'clothes': 440,
 'early': 441,
 'sheep': 442,
 'ghebreyesus': 443,
 'supercomputer': 444,
 'v.': 445,
 'ram': 446,
 'children’s': 447,
 'hippocrates': 448,
 'atomic': 449,
 'people': 450,
 'biggest': 451,
 'child': 452,
 'capital': 453,
 'over': 454,
 'sleep': 455,
 'honeybees': 456,
 'processing': 457,
 'oscar': 458,
 'name': 459,
 'mice': 460,
 'hydrochloric': 461,
 'week': 462,
 '“grand': 463,
 'hydrogen': 464,
 'random': 465,
 'teaches': 466,
 'world,': 467,
 'mathematics”': 468,
 'microsoft': 469,
 'necessary': 470,
 'j': 471,
 'connected': 472,
 'powell': 473,
 'countries': 474,
 'bones.': 475,
 'a.p.j.': 476,
 'discover': 477,
 'backward': 478,
 '“oak': 479,
 'gravity': 480,
 'dr': 481,
 'turns': 482,
 '1': 483,
 'state': 484,
 'diamond': 485,
 'super': 486,
 '“blue': 487,
 'last': 488,
 'some': 489,
 'related': 490,
 'desert”': 491,
 'pack': 492,
 'sir': 493,
 'painter': 494,
 'tungsten': 495,
 '_____.': 496,
 'indicate': 497,
 '90˚': 498,
 '1985': 499,
 'home': 500,
 'producer': 501,
 'nath': 502,
 'summer': 503,
 'geoffrey': 504,
 'bohag': 505,
 'throat,': 506,
 'where': 507,
 'adiga': 508,
 'milky': 509,
 'slowest': 510,
 'african': 511,
 'hill': 512,
 'you': 513,
 'brazilian': 514,
 'origami': 515,
 'spain': 516,
 'dandi': 517,
 'types': 518,
 'uae': 519,
 'concept': 520,
 'your': 521,
 '0': 522,
 'ivory': 523,
 'conducts': 524,
 'nyctophobia': 525,
 'directions': 526,
 'neil': 527,
 'vegetables': 528,
 'ground': 529,
 'pisa': 530,
 'adam': 531,
 'located': 532,
 'logie': 533,
 'car': 534,
 '2020': 535,
 'look': 536,
 'pentagon': 537,
 'bulb': 538,
 'call': 539,
 'buttons.': 540,
 'video': 541,
 'atmosphere.': 542,
 'this': 543,
 'helm': 544,
 'indira': 545,
 'wednesday': 546,
 'inventor,': 547,
 'equator': 548,
 'her': 549,
 'modern': 550,
 'bharat': 551,
 '&': 552,
 'planet”': 553,
 '27': 554,
 'eye': 555,
 '50': 556,
 'layer': 557,
 'ii': 558,
 'rises': 559,
 'has': 560,
 '9999': 561,
 'goes': 562,
 'crosses': 563,
 'provider,': 564,
 'ratio': 565,
 'long': 566,
 '1930': 567,
 'desert': 568,
 'garden': 569,
 'chemical': 570,
 'articles': 571,
 'tokyo': 572,
 'called': 573,
 'corners': 574,
 'magic': 575,
 'traffic': 576,
 'system': 577,
 'visvesaraya': 578,
 'mercury': 579,
 'side': 580,
 'brightest': 581,
 'tale': 582,
 'plath': 583,
 'chlorophyll': 584,
 'healthy': 585,
 'yerevan': 586,
 'p.j.': 587,
 'winner': 588,
 'young': 589,
 'oxygen': 590,
 'coffee': 591,
 'world.': 592,
 'head': 593,
 'furniture': 594,
 '34': 595,
 'at': 596,
 'sunburn.': 597,
 'april': 598,
 'book—jungle': 599,
 'manatees': 600,
 'patna,': 601,
 'lots': 602,
 'sky.': 603,
 'b,': 604,
 'buddhists': 605,
 'usa': 606,
 'what': 607,
 'like': 608,
 'submerged': 609,
 'using': 610,
 'flow': 611,
 'banks': 612,
 'yellow,': 613,
 'sachin': 614,
 'km/sec': 615,
 'layers': 616,
 'game,': 617,
 'alva': 618,
 'raman,': 619,
 'equal.': 620,
 'series': 621,
 'powder': 622,
 'mario': 623,
 'einstein': 624,
 'after': 625,
 'sets': 626,
 'little': 627,
 'eyes': 628,
 'nehwal': 629,
 'punjab': 630,
 'gautham': 631,
 'we': 632,
 'dice': 633,
 'kipling': 634,
 'argentina': 635,
 'island': 636,
 'giza': 637,
 'china,': 638,
 '_______.': 639,
 '1884': 640,
 'rudyard': 641,
 'international': 642,
 'fire.': 643,
 '1896': 644,
 'teeth': 645,
 'tea': 646,
 'north': 647,
 'pigment': 648,
 'american': 649,
 'taj': 650,
 'grow': 651,
 'stay': 652,
 'brother,': 653,
 'story': 654,
 'toes.': 655,
 'orville': 656,
 'citric': 657,
 'orange,': 658,
 'wilhelm': 659,
 'bear’': 660,
 '2,': 661,
 'no': 662,
 'roots': 663,
 'divas': 664,
 'computer”': 665,
 'slam”': 666,
 'infinite': 667,
 'stripes’': 668,
 'color': 669,
 'nile”': 670,
 'dozen': 671,
 '______': 672,
 '“sorrow': 673,
 'cannot': 674,
 'emirates': 675,
 'surface': 676,
 'board': 677,
 'century': 678,
 'flowers’': 679,
 'resource': 680,
 'violin': 681,
 '“kitchen': 682,
 'invented': 683,
 'arthur': 684,
 'coelho': 685,
 'elephants”': 686,
 'fear': 687,
 'city”': 688,
 'president': 689,
 'games': 690,
 '“wait”': 691,
 'mesosphere,': 692,
 'infamous': 693,
 'ore': 694,
 'cricketer': 695,
 '6': 696,
 '16': 697,
 'virat': 698,
 'sight': 699,
 'blind.': 700,
 'zoo': 701,
 '“red': 702,
 'scotland': 703,
 'vegetable': 704,
 'july,': 705,
 '‘discovery': 706,
 'music': 707,
 'why': 708,
 'restoration': 709,
 'natural': 710,
 'mark': 711,
 'much': 712,
 'lord': 713,
 '‘great': 714,
 'ritchie': 715,
 'leonardo': 716,
 'd.12': 717,
 '2019': 718,
 'benjamin': 719,
 'relativity': 720,
 'roger': 721,
 'galaxy': 722,
 'china”': 723,
 'galaxies': 724,
 'protons': 725,
 'map': 726,
 'relate': 727,
 'four': 728,
 'moscow': 729,
 'surgeon,': 730,
 'morocco': 731,
 'dentist': 732,
 'kept': 733,
 'bolivia': 734,
 'data': 735,
 'belgium': 736,
 'frogs': 737,
 'chocolate': 738,
 'india”': 739,
 'jesus': 740,
 'prickle': 741,
 'raindrop': 742,
 'julian': 743,
 'peru': 744,
 'wags': 745,
 'lima': 746,
 'how': 747,
 'postage': 748,
 'asian': 749,
 'held': 750,
 'market': 751,
 'money': 752,
 'dog,': 753,
 'sharma': 754,
 'present': 755,
 'lengths': 756,
 '12': 757,
 'opposite': 758,
 'medicine': 759,
 'bhai': 760,
 'europe': 761,
 'wilbur': 762,
 'women': 763,
 'igloo': 764,
 'days': 765,
 'pratyush': 766,
 'usain': 767,
 'sty': 768,
 'charles': 769,
 '“indian': 770,
 '33': 771,
 'algae': 772,
 'turn': 773,
 'car,': 774,
 'olympics': 775,
 'whale': 776,
 'troposphere': 777,
 'vijayalaya': 778,
 'extinct': 779,
 'another': 780,
 'true': 781,
 '________________': 782,
 '29': 783,
 'chaucer': 784,
 'butterfly': 785,
 'do': 786,
 'rashtriya': 787,
 'elephant,': 788,
 'brics,': 789,
 '9': 790,
 'sphygmomanometer': 791,
 'homi': 792,
 'blair': 793,
 'modi': 794,
 'only': 795,
 'maximum': 796,
 'got': 797,
 'deposit': 798,
 'cooks': 799,
 'age': 800,
 'karmakar': 801,
 'bhat': 802,
 'subscriber': 803,
 'tim': 804,
 'vyommitra': 805,
 'wrote': 806,
 'asia': 807,
 'nile': 808,
 'very': 809,
 'mountain': 810,
 'layers.': 811,
 'olympic': 812,
 'measure': 813,
 'life,': 814,
 'orbit': 815,
 'gypsum': 816,
 '4': 817,
 'john': 818,
 'through': 819,
 'colors': 820,
 'in': 821,
 'reputed': 822,
 'north,': 823,
 'fly': 824,
 'humps.': 825,
 'wisdom': 826,
 'two': 827,
 'chess,': 828,
 'drives': 829,
 'suess': 830,
 '5th': 831,
 'arundhati': 832,
 'whom': 833,
 'create': 834,
 '“god': 835,
 'joey': 836,
 'going': 837,
 'potato,': 838,
 'their': 839,
 'even': 840,
 'india.': 841,
 'pen': 842,
 'brother': 843,
 '24': 844,
 'wings': 845,
 'established': 846,
 'maternal': 847,
 'fundamental': 848,
 'statue': 849,
 'devi': 850,
 'top': 851,
 'january,': 852,
 'football': 853,
 'seasons': 854,
 'asia,': 855,
 '5': 856,
 'neeraj': 857,
 'mickey': 858,
 'brazil': 859,
 'prasad': 860,
 'small': 861,
 'sea': 862,
 'woollen': 863,
 '“financial': 864,
 'e,': 865,
 'wrist': 866,
 'rai': 867,
 'ganga': 868,
 'electricity': 869,
 'steam': 870,
 'belly': 871,
 '’': 872,
 'coldest': 873,
 'louvre': 874,
 'sonar': 875,
 'whales': 876,
 'beautiful': 877,
 'carpenter,': 878,
 'season': 879,
 'uranus': 880,
 'calcutta': 881,
 'product': 882,
 'seconds': 883,
 'named': 884,
 'planet,': 885,
 'known': 886,
 'square': 887,
 'hearts.': 888,
 'won': 889,
 'start': 890,
 'economics': 891,
 '‘festival': 892,
 'did': 893,
 'assam': 894,
 'wound': 895,
 'cells': 896,
 'cartoon': 897,
 'comes': 898,
 'potato': 899,
 'novelist': 900,
 'helps': 901,
 'calf': 902,
 'hockey': 903,
 'patients': 904,
 'use': 905,
 'bonaparte': 906,
 'wheels': 907,
 'global': 908,
 'tereshkova': 909,
 'winter': 910,
 '144': 911,
 'which': 912,
 'lights': 913,
 '1939-1945': 914,
 'november': 915,
 'telephone': 916,
 'homoeopathy': 917,
 'girl': 918,
 'any': 919,
 'wwi': 920,
 'nitrous': 921,
 '‘panchathantra’': 922,
 '1908': 923,
 'marconi': 924,
 'breathe': 925,
 'anopheles': 926,
 'dubai,': 927,
 'watt': 928,
 'thief': 929,
 'mahatma': 930,
 'messi': 931,
 'shapes': 932,
 'ginger': 933,
 'lexicographer': 934,
 'grandfather': 935,
 '‘fruit': 936,
 'line': 937,
 'pressure': 938,
 'temperature': 939,
 'authored': 940,
 'moisture': 941,
 'glucose': 942,
 'solar': 943,
 'sperm': 944,
 'arachnophobia': 945,
 'badminton': 946,
 'below': 947,
 'neptune': 948,
 'health': 949,
 'kennel': 950,
 '999': 951,
 'owl': 952,
 'largest': 953,
 'george': 954,
 'columbus': 955,
 'somniferum': 956,
 'valentina': 957,
 'holes': 958,
 'strange': 959,
 'situated': 960,
 'chatterjee': 961,
 'narnia”': 962,
 'belong': 963,
 'potter': 964,
 'gold': 965,
 'bang': 966,
 'sum': 967,
 'ascorbic': 968,
 'post': 969,
 'table': 970,
 'belongs': 971,
 'rupee': 972,
 'colour': 973,
 'pacific': 974,
 'lewis': 975,
 'hours': 976,
 'three-digit': 977,
 'may,': 978,
 'terms’': 979,
 'tower': 980,
 'laika,': 981,
 'backwards': 982,
 'countries,': 983,
 'they': 984,
 'day': 985,
 'bat,': 986,
 'sylvia': 987,
 'care': 988,
 'millimeters': 989,
 'dynasty': 990,
 'have': 991,
 'ten': 992,
 'satellite': 993,
 'triangle': 994,
 'telescope': 995,
 'penicillin': 996,
 'angles': 997,
 '82': 998,
 '14th': 999,
 ...}

In [317]:
df['token_q'] = df['question'].apply(lambda text: [vocabulary.get(word, 1) for word in tokenize(text)])
df['token_a'] = df['answer'].apply(lambda text: [vocabulary.get(word, 1) for word in tokenize(text)])

In [318]:
df['token_a'] = [[2] + sent + [3] for sent in df['token_a']]

In [319]:
df['token_q'] = [sent + [0]*(max_q_len - len(sent))for sent in df['token_q']]

In [320]:
df['token_a'] = [sent + [0]*(max_a_len - len(sent))for sent in df['token_a']]

In [321]:
df

,question,answer,token_q,token_a
0,How many days do we have in a week?,Seven,"[747, 1762, 765, 786, 632, 991, 821, 56, 462, ...","[2, 2169, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
1,How many days are there in a normal year?,365 (not a leap year),"[747, 1762, 765, 1801, 2154, 821, 56, 1659, 11...","[2, 1690, 1592, 56, 1047, 1127, 3, 0, 0, 0, 0,..."
2,How many colors are there in a rainbow?,7,"[747, 1762, 820, 1801, 2154, 821, 56, 1186, 0,...","[2, 1329, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
3,Which animal is known as the ‘Ship of the Dese...,Camel,"[912, 1422, 2186, 886, 2167, 354, 1390, 110, 3...","[2, 1532, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
4,How many letters are there in the English alph...,26,"[747, 1762, 39, 1801, 2154, 821, 354, 114, 116...","[2, 311, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0..."
...,...,...,...,...
925,Where are the HeadQuarters of UNESCO?,"Paris, France","[507, 1801, 354, 1053, 110, 1758, 0, 0, 0, 0, ...","[2, 198, 2012, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0..."
926,Which are the colors of the rings of the Olymp...,"Black, Red, Blue, Green, and Yellow","[912, 1801, 354, 820, 110, 354, 1814, 110, 354...","[2, 1854, 130, 1467, 2163, 87, 2024, 3, 0, 0, ..."
927,Who invented ‘Lift’?,Elisha Graves Otis,"[396, 683, 1543, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...","[2, 1664, 1891, 1892, 3, 0, 0, 0, 0, 0, 0, 0, ..."
928,Which river crosses the equator twice?,Congo River,"[912, 1207, 563, 354, 548, 1298, 0, 0, 0, 0, 0...","[2, 334, 1207, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0..."
929,Which is the device used to locate submerged o...,SONAR,"[912, 2186, 354, 1882, 1862, 1773, 310, 609, 2...","[2, 875, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0..."

In [322]:
max_q_len = max(len(q) for q in df['token_q'])
max_a_len = max(len(a) for a in df['token_a'])

In [323]:
print(max_q_len, max_a_len)

28 21

In [324]:
vocabulary

{'<PAD>': 0,
 '<UNK>': 1,
 '<SOS>': 2,
 '<EOS>': 3,
 'asking': 4,
 'sun': 5,
 'saarc': 6,
 'norway': 7,
 'stars': 8,
 'into': 9,
 'none': 10,
 'founder': 11,
 'archimedes': 12,
 'people.': 13,
 'strings': 14,
 'full': 15,
 '916': 16,
 'will': 17,
 'reappointed': 18,
 'bay': 19,
 '27*0': 20,
 'edison': 21,
 'rbi': 22,
 'cow': 23,
 'lies': 24,
 'was': 25,
 'plant': 26,
 'year.': 27,
 'buddhist': 28,
 'berners-lee': 29,
 'beehives': 30,
 'thousand': 31,
 'nuclear': 32,
 'common': 33,
 'tedros': 34,
 'history': 35,
 'carry': 36,
 'a.': 37,
 'mango': 38,
 'letters': 39,
 'vowels': 40,
 'kalaam,': 41,
 'baku': 42,
 'cross': 43,
 'land': 44,
 'hat-trick': 45,
 'york': 46,
 'mother,': 47,
 'robot': 48,
 'x-rays': 49,
 'ella': 50,
 'frescos': 51,
 '2': 52,
 'treats': 53,
 'beri-beri': 54,
 'eraser,': 55,
 'a': 56,
 'read-only': 57,
 '____________.': 58,
 'environment': 59,
 'ryder': 60,
 'malic': 61,
 'atmosphere': 62,
 'council': 63,
 'thomas': 64,
 'plants': 65,
 'nirvana': 66,
 'sometimes': 67,
 'sky': 68,
 'distance': 69,
 'eggs': 70,
 'am': 71,
 'philadelphia': 72,
 'titan': 73,
 'food': 74,
 'its': 75,
 'sports': 76,
 'players': 77,
 'pigeon,': 78,
 'boat': 79,
 'twin': 80,
 'violet,': 81,
 'cephalopod': 82,
 'absorbed': 83,
 'fox': 84,
 'bank': 85,
 'position': 86,
 'and': 87,
 '______.': 88,
 'euclid': 89,
 'standard': 90,
 'similar': 91,
 'years.': 92,
 'ink': 93,
 'country': 94,
 'reduced': 95,
 'lines': 96,
 '3,00,000': 97,
 'paulo': 98,
 '‘ramayana’': 99,
 'union': 100,
 'national': 101,
 'harvest': 102,
 'humanoid': 103,
 'soda': 104,
 'gases': 105,
 'forest': 106,
 'kingdom': 107,
 'ozone': 108,
 'sharks': 109,
 'of': 110,
 'calcium': 111,
 'rom': 112,
 'gautama': 113,
 'english': 114,
 'author': 115,
 'location': 116,
 'guards': 117,
 'teacher': 118,
 'cat': 119,
 'barrier': 120,
 'baird': 121,
 'victor': 122,
 'cyber': 123,
 'prix': 124,
 'court': 125,
 'popular': 126,
 'zeroes': 127,
 'give': 128,
 'horses': 129,
 'red,': 130,
 'ekta': 131,
 'ganymede': 132,
 's': 133,
 'opium': 134,
 'please': 135,
 'during': 136,
 'chopra': 137,
 'supply': 138,
 'invests': 139,
 'pencil,': 140,
 '2020.': 141,
 'tree': 142,
 'dioxide': 143,
 'revolve': 144,
 'donor”': 145,
 '“gift': 146,
 'hypochlorite,': 147,
 'phycology': 148,
 'sound': 149,
 'azerbaijan': 150,
 'prime': 151,
 'k': 152,
 'water': 153,
 'hen': 154,
 'vitamin”': 155,
 'mt.': 156,
 'made': 157,
 'coco': 158,
 '21': 159,
 'turkey': 160,
 'get': 161,
 'times': 162,
 'tropical': 163,
 'warming': 164,
 'painted': 165,
 'anniversary': 166,
 'cups': 167,
 'fire': 168,
 'metal': 169,
 'colours': 170,
 'yamuna': 171,
 'composed': 172,
 'buddha': 173,
 'most': 174,
 'award': 175,
 'place': 176,
 'stomata': 177,
 'coconut': 178,
 'own': 179,
 'air': 180,
 'geometry”': 181,
 'rights': 182,
 'belt': 183,
 'introduced': 184,
 'mataram': 185,
 'process': 186,
 'taste': 187,
 'wool': 188,
 'pataliputra': 189,
 'sikh': 190,
 'number': 191,
 'vikram': 192,
 'guglielmo': 193,
 'christopher': 194,
 'raman': 195,
 'human': 196,
 'iron': 197,
 'paris,': 198,
 'diwali': 199,
 'when': 200,
 'developed': 201,
 'scientist': 202,
 'p': 203,
 'lives': 204,
 'hosted': 205,
 'vacuum': 206,
 'awarded': 207,
 'seas': 208,
 'sardar': 209,
 'manipur': 210,
 'earthquakes': 211,
 'lala': 212,
 'ophidiophobia': 213,
 'among': 214,
 'j.k.': 215,
 'obtained': 216,
 '1914': 217,
 'country”': 218,
 'kidneys': 219,
 'goat': 220,
 'hexagon': 221,
 'baer': 222,
 'positioning': 223,
 'wonderland,': 224,
 'zones': 225,
 'reserve': 226,
 'lionel': 227,
 'lacrosse/ice': 228,
 'helium': 229,
 '‘class’': 230,
 'may': 231,
 'commonly': 232,
 'bhagat': 233,
 'sistine': 234,
 'pound': 235,
 'caesar”': 236,
 'ruble': 237,
 'sterling': 238,
 'calculate': 239,
 'august': 240,
 'armstrong': 241,
 'develop': 242,
 'meteorology': 243,
 'approximate': 244,
 'begin': 245,
 'kitten': 246,
 'platelets': 247,
 'isro': 248,
 'hummingbird': 249,
 'thiruvananthapuram': 250,
 'christmas': 251,
 '1903': 252,
 'cinderella': 253,
 'ship': 254,
 '__________': 255,
 'aladdin': 256,
 'carle': 257,
 'kohli': 258,
 'saina': 259,
 'soil': 260,
 'polo': 261,
 'memory': 262,
 'indicates': 263,
 'states': 264,
 'decade': 265,
 'bowl’': 266,
 'carp': 267,
 'golf': 268,
 'years': 269,
 'eats': 270,
 'library': 271,
 'non-metal': 272,
 'brown': 273,
 'fe': 274,
 '_________': 275,
 'fight': 276,
 'mamba': 277,
 '5.75': 278,
 '1914-1918': 279,
 'footballer': 280,
 'march,': 281,
 'kanishka': 282,
 'specialist.': 283,
 'c.s.': 284,
 'mbbs': 285,
 'italy': 286,
 'calendar': 287,
 'jupiter,': 288,
 '22/7': 289,
 'launch': 290,
 'astronaut': 291,
 'moons.': 292,
 'produced': 293,
 'stadium': 294,
 'dennis': 295,
 'mars': 296,
 'bill': 297,
 '______________': 298,
 'carroll': 299,
 'fourth': 300,
 'giraffe': 301,
 'theory': 302,
 'mother': 303,
 'same': 304,
 'building,': 305,
 'franklin': 306,
 '3600': 307,
 'milkha': 308,
 'lightest': 309,
 'locate': 310,
 '26': 311,
 'gates': 312,
 'lamp': 313,
 'copper': 314,
 'islands': 315,
 'dove': 316,
 'rowland': 317,
 'walk': 318,
 'colt': 319,
 'abundant': 320,
 'rain': 321,
 'bahrain': 322,
 'o,': 323,
 'stick': 324,
 'manuel': 325,
 'charminar': 326,
 'deadly': 327,
 '2011': 328,
 'leaning': 329,
 'delhi': 330,
 'organs': 331,
 'bangladesh': 332,
 'dinosaur,': 333,
 'congo': 334,
 '10+4': 335,
 'introduce': 336,
 '“little': 337,
 'equals': 338,
 'spokes': 339,
 'life': 340,
 'complete': 341,
 'brain.': 342,
 'james': 343,
 '–': 344,
 'born': 345,
 'tuesday': 346,
 'up': 347,
 '48': 348,
 'computer.': 349,
 'brain’s': 350,
 'need': 351,
 'patel': 352,
 '“charlie': 353,
 'the': 354,
 'hypertext': 355,
 'once': 356,
 'wheel': 357,
 'fingernail': 358,
 'nitrogen': 359,
 'continue': 360,
 'bachelor': 361,
 'ship,': 362,
 'eruption': 363,
 'autumn': 364,
 'leaf': 365,
 'throw': 366,
 'copenhagen': 367,
 'east': 368,
 'sky”': 369,
 'nutrients': 370,
 'placed': 371,
 'care!': 372,
 'four-digit': 373,
 'orient': 374,
 'bear': 375,
 'letter': 376,
 'hammer': 377,
 'onam': 378,
 'angkor': 379,
 'meridiem': 380,
 'biwa': 381,
 'spratly': 382,
 'weight': 383,
 'that': 384,
 '___': 385,
 'monument': 386,
 'vehicle': 387,
 'sahara': 388,
 'newton,': 389,
 '3': 390,
 'hour': 391,
 'highest': 392,
 'tibet': 393,
 'resulting': 394,
 'kangaroo': 395,
 'who': 396,
 'atlantic': 397,
 'five': 398,
 'base': 399,
 'language': 400,
 'caddie': 401,
 'cup': 402,
 'blink': 403,
 'nehru': 404,
 'organization,': 405,
 'persian': 406,
 'china': 407,
 'acute': 408,
 'geometric': 409,
 'world': 410,
 'nobel': 411,
 'equal': 412,
 'drama': 413,
 '1.618': 414,
 'access': 415,
 'source': 416,
 'owned': 417,
 '‘wings': 418,
 'parts': 419,
 'non-quadrilateral': 420,
 'everest': 421,
 'ratna': 422,
 'identity': 423,
 'exosphere,': 424,
 'road': 425,
 'africa': 426,
 'program': 427,
 'cow,': 428,
 'apj': 429,
 'thailand': 430,
 'back': 431,
 'wireless': 432,
 'fought': 433,
 'mosquitoes': 434,
 'kanchenjunga': 435,
 'excess': 436,
 'goitre': 437,
 'freshwater': 438,
 'space': 439,
 'clothes': 440,
 'early': 441,
 'sheep': 442,
 'ghebreyesus': 443,
 'supercomputer': 444,
 'v.': 445,
 'ram': 446,
 'children’s': 447,
 'hippocrates': 448,
 'atomic': 449,
 'people': 450,
 'biggest': 451,
 'child': 452,
 'capital': 453,
 'over': 454,
 'sleep': 455,
 'honeybees': 456,
 'processing': 457,
 'oscar': 458,
 'name': 459,
 'mice': 460,
 'hydrochloric': 461,
 'week': 462,
 '“grand': 463,
 'hydrogen': 464,
 'random': 465,
 'teaches': 466,
 'world,': 467,
 'mathematics”': 468,
 'microsoft': 469,
 'necessary': 470,
 'j': 471,
 'connected': 472,
 'powell': 473,
 'countries': 474,
 'bones.': 475,
 'a.p.j.': 476,
 'discover': 477,
 'backward': 478,
 '“oak': 479,
 'gravity': 480,
 'dr': 481,
 'turns': 482,
 '1': 483,
 'state': 484,
 'diamond': 485,
 'super': 486,
 '“blue': 487,
 'last': 488,
 'some': 489,
 'related': 490,
 'desert”': 491,
 'pack': 492,
 'sir': 493,
 'painter': 494,
 'tungsten': 495,
 '_____.': 496,
 'indicate': 497,
 '90˚': 498,
 '1985': 499,
 'home': 500,
 'producer': 501,
 'nath': 502,
 'summer': 503,
 'geoffrey': 504,
 'bohag': 505,
 'throat,': 506,
 'where': 507,
 'adiga': 508,
 'milky': 509,
 'slowest': 510,
 'african': 511,
 'hill': 512,
 'you': 513,
 'brazilian': 514,
 'origami': 515,
 'spain': 516,
 'dandi': 517,
 'types': 518,
 'uae': 519,
 'concept': 520,
 'your': 521,
 '0': 522,
 'ivory': 523,
 'conducts': 524,
 'nyctophobia': 525,
 'directions': 526,
 'neil': 527,
 'vegetables': 528,
 'ground': 529,
 'pisa': 530,
 'adam': 531,
 'located': 532,
 'logie': 533,
 'car': 534,
 '2020': 535,
 'look': 536,
 'pentagon': 537,
 'bulb': 538,
 'call': 539,
 'buttons.': 540,
 'video': 541,
 'atmosphere.': 542,
 'this': 543,
 'helm': 544,
 'indira': 545,
 'wednesday': 546,
 'inventor,': 547,
 'equator': 548,
 'her': 549,
 'modern': 550,
 'bharat': 551,
 '&': 552,
 'planet”': 553,
 '27': 554,
 'eye': 555,
 '50': 556,
 'layer': 557,
 'ii': 558,
 'rises': 559,
 'has': 560,
 '9999': 561,
 'goes': 562,
 'crosses': 563,
 'provider,': 564,
 'ratio': 565,
 'long': 566,
 '1930': 567,
 'desert': 568,
 'garden': 569,
 'chemical': 570,
 'articles': 571,
 'tokyo': 572,
 'called': 573,
 'corners': 574,
 'magic': 575,
 'traffic': 576,
 'system': 577,
 'visvesaraya': 578,
 'mercury': 579,
 'side': 580,
 'brightest': 581,
 'tale': 582,
 'plath': 583,
 'chlorophyll': 584,
 'healthy': 585,
 'yerevan': 586,
 'p.j.': 587,
 'winner': 588,
 'young': 589,
 'oxygen': 590,
 'coffee': 591,
 'world.': 592,
 'head': 593,
 'furniture': 594,
 '34': 595,
 'at': 596,
 'sunburn.': 597,
 'april': 598,
 'book—jungle': 599,
 'manatees': 600,
 'patna,': 601,
 'lots': 602,
 'sky.': 603,
 'b,': 604,
 'buddhists': 605,
 'usa': 606,
 'what': 607,
 'like': 608,
 'submerged': 609,
 'using': 610,
 'flow': 611,
 'banks': 612,
 'yellow,': 613,
 'sachin': 614,
 'km/sec': 615,
 'layers': 616,
 'game,': 617,
 'alva': 618,
 'raman,': 619,
 'equal.': 620,
 'series': 621,
 'powder': 622,
 'mario': 623,
 'einstein': 624,
 'after': 625,
 'sets': 626,
 'little': 627,
 'eyes': 628,
 'nehwal': 629,
 'punjab': 630,
 'gautham': 631,
 'we': 632,
 'dice': 633,
 'kipling': 634,
 'argentina': 635,
 'island': 636,
 'giza': 637,
 'china,': 638,
 '_______.': 639,
 '1884': 640,
 'rudyard': 641,
 'international': 642,
 'fire.': 643,
 '1896': 644,
 'teeth': 645,
 'tea': 646,
 'north': 647,
 'pigment': 648,
 'american': 649,
 'taj': 650,
 'grow': 651,
 'stay': 652,
 'brother,': 653,
 'story': 654,
 'toes.': 655,
 'orville': 656,
 'citric': 657,
 'orange,': 658,
 'wilhelm': 659,
 'bear’': 660,
 '2,': 661,
 'no': 662,
 'roots': 663,
 'divas': 664,
 'computer”': 665,
 'slam”': 666,
 'infinite': 667,
 'stripes’': 668,
 'color': 669,
 'nile”': 670,
 'dozen': 671,
 '______': 672,
 '“sorrow': 673,
 'cannot': 674,
 'emirates': 675,
 'surface': 676,
 'board': 677,
 'century': 678,
 'flowers’': 679,
 'resource': 680,
 'violin': 681,
 '“kitchen': 682,
 'invented': 683,
 'arthur': 684,
 'coelho': 685,
 'elephants”': 686,
 'fear': 687,
 'city”': 688,
 'president': 689,
 'games': 690,
 '“wait”': 691,
 'mesosphere,': 692,
 'infamous': 693,
 'ore': 694,
 'cricketer': 695,
 '6': 696,
 '16': 697,
 'virat': 698,
 'sight': 699,
 'blind.': 700,
 'zoo': 701,
 '“red': 702,
 'scotland': 703,
 'vegetable': 704,
 'july,': 705,
 '‘discovery': 706,
 'music': 707,
 'why': 708,
 'restoration': 709,
 'natural': 710,
 'mark': 711,
 'much': 712,
 'lord': 713,
 '‘great': 714,
 'ritchie': 715,
 'leonardo': 716,
 'd.12': 717,
 '2019': 718,
 'benjamin': 719,
 'relativity': 720,
 'roger': 721,
 'galaxy': 722,
 'china”': 723,
 'galaxies': 724,
 'protons': 725,
 'map': 726,
 'relate': 727,
 'four': 728,
 'moscow': 729,
 'surgeon,': 730,
 'morocco': 731,
 'dentist': 732,
 'kept': 733,
 'bolivia': 734,
 'data': 735,
 'belgium': 736,
 'frogs': 737,
 'chocolate': 738,
 'india”': 739,
 'jesus': 740,
 'prickle': 741,
 'raindrop': 742,
 'julian': 743,
 'peru': 744,
 'wags': 745,
 'lima': 746,
 'how': 747,
 'postage': 748,
 'asian': 749,
 'held': 750,
 'market': 751,
 'money': 752,
 'dog,': 753,
 'sharma': 754,
 'present': 755,
 'lengths': 756,
 '12': 757,
 'opposite': 758,
 'medicine': 759,
 'bhai': 760,
 'europe': 761,
 'wilbur': 762,
 'women': 763,
 'igloo': 764,
 'days': 765,
 'pratyush': 766,
 'usain': 767,
 'sty': 768,
 'charles': 769,
 '“indian': 770,
 '33': 771,
 'algae': 772,
 'turn': 773,
 'car,': 774,
 'olympics': 775,
 'whale': 776,
 'troposphere': 777,
 'vijayalaya': 778,
 'extinct': 779,
 'another': 780,
 'true': 781,
 '________________': 782,
 '29': 783,
 'chaucer': 784,
 'butterfly': 785,
 'do': 786,
 'rashtriya': 787,
 'elephant,': 788,
 'brics,': 789,
 '9': 790,
 'sphygmomanometer': 791,
 'homi': 792,
 'blair': 793,
 'modi': 794,
 'only': 795,
 'maximum': 796,
 'got': 797,
 'deposit': 798,
 'cooks': 799,
 'age': 800,
 'karmakar': 801,
 'bhat': 802,
 'subscriber': 803,
 'tim': 804,
 'vyommitra': 805,
 'wrote': 806,
 'asia': 807,
 'nile': 808,
 'very': 809,
 'mountain': 810,
 'layers.': 811,
 'olympic': 812,
 'measure': 813,
 'life,': 814,
 'orbit': 815,
 'gypsum': 816,
 '4': 817,
 'john': 818,
 'through': 819,
 'colors': 820,
 'in': 821,
 'reputed': 822,
 'north,': 823,
 'fly': 824,
 'humps.': 825,
 'wisdom': 826,
 'two': 827,
 'chess,': 828,
 'drives': 829,
 'suess': 830,
 '5th': 831,
 'arundhati': 832,
 'whom': 833,
 'create': 834,
 '“god': 835,
 'joey': 836,
 'going': 837,
 'potato,': 838,
 'their': 839,
 'even': 840,
 'india.': 841,
 'pen': 842,
 'brother': 843,
 '24': 844,
 'wings': 845,
 'established': 846,
 'maternal': 847,
 'fundamental': 848,
 'statue': 849,
 'devi': 850,
 'top': 851,
 'january,': 852,
 'football': 853,
 'seasons': 854,
 'asia,': 855,
 '5': 856,
 'neeraj': 857,
 'mickey': 858,
 'brazil': 859,
 'prasad': 860,
 'small': 861,
 'sea': 862,
 'woollen': 863,
 '“financial': 864,
 'e,': 865,
 'wrist': 866,
 'rai': 867,
 'ganga': 868,
 'electricity': 869,
 'steam': 870,
 'belly': 871,
 '’': 872,
 'coldest': 873,
 'louvre': 874,
 'sonar': 875,
 'whales': 876,
 'beautiful': 877,
 'carpenter,': 878,
 'season': 879,
 'uranus': 880,
 'calcutta': 881,
 'product': 882,
 'seconds': 883,
 'named': 884,
 'planet,': 885,
 'known': 886,
 'square': 887,
 'hearts.': 888,
 'won': 889,
 'start': 890,
 'economics': 891,
 '‘festival': 892,
 'did': 893,
 'assam': 894,
 'wound': 895,
 'cells': 896,
 'cartoon': 897,
 'comes': 898,
 'potato': 899,
 'novelist': 900,
 'helps': 901,
 'calf': 902,
 'hockey': 903,
 'patients': 904,
 'use': 905,
 'bonaparte': 906,
 'wheels': 907,
 'global': 908,
 'tereshkova': 909,
 'winter': 910,
 '144': 911,
 'which': 912,
 'lights': 913,
 '1939-1945': 914,
 'november': 915,
 'telephone': 916,
 'homoeopathy': 917,
 'girl': 918,
 'any': 919,
 'wwi': 920,
 'nitrous': 921,
 '‘panchathantra’': 922,
 '1908': 923,
 'marconi': 924,
 'breathe': 925,
 'anopheles': 926,
 'dubai,': 927,
 'watt': 928,
 'thief': 929,
 'mahatma': 930,
 'messi': 931,
 'shapes': 932,
 'ginger': 933,
 'lexicographer': 934,
 'grandfather': 935,
 '‘fruit': 936,
 'line': 937,
 'pressure': 938,
 'temperature': 939,
 'authored': 940,
 'moisture': 941,
 'glucose': 942,
 'solar': 943,
 'sperm': 944,
 'arachnophobia': 945,
 'badminton': 946,
 'below': 947,
 'neptune': 948,
 'health': 949,
 'kennel': 950,
 '999': 951,
 'owl': 952,
 'largest': 953,
 'george': 954,
 'columbus': 955,
 'somniferum': 956,
 'valentina': 957,
 'holes': 958,
 'strange': 959,
 'situated': 960,
 'chatterjee': 961,
 'narnia”': 962,
 'belong': 963,
 'potter': 964,
 'gold': 965,
 'bang': 966,
 'sum': 967,
 'ascorbic': 968,
 'post': 969,
 'table': 970,
 'belongs': 971,
 'rupee': 972,
 'colour': 973,
 'pacific': 974,
 'lewis': 975,
 'hours': 976,
 'three-digit': 977,
 'may,': 978,
 'terms’': 979,
 'tower': 980,
 'laika,': 981,
 'backwards': 982,
 'countries,': 983,
 'they': 984,
 'day': 985,
 'bat,': 986,
 'sylvia': 987,
 'care': 988,
 'millimeters': 989,
 'dynasty': 990,
 'have': 991,
 'ten': 992,
 'satellite': 993,
 'triangle': 994,
 'telescope': 995,
 'penicillin': 996,
 'angles': 997,
 '82': 998,
 '14th': 999,
 ...}

In [325]:
def text2tok(text, vocabulary):
    return [vocabulary.get(word, vocabulary['<UNK>']) for word in tokenize(text)]

In [326]:
text2tok("what is apple?", vocabulary)

[607, 2186, 1894]

In [327]:
class datalao(Dataset):
    def __init__(self, questions, answers):
        self.q = questions
        self.a = answers

    def __len__(self):
        return self.q.shape[0]

    def __getitem__(self, idx):
        return torch.tensor(self.q[idx]), torch.tensor(self.a[idx])

In [328]:
dataset = datalao(df['token_q'], df['token_a'])

In [329]:
dataset[0]

(tensor([ 747, 1762,  765,  786,  632,  991,  821,   56,  462,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0]),
 tensor([   2, 2169,    3,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0]))

In [330]:
train_load = DataLoader(dataset, batch_size = 4, shuffle = True)

In [331]:
for q, a in train_load:
    print(q,a)

tensor([[  56, 1653, 1009,  856, 1340, 2186,  573,   56, 1524,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0],
        [ 912, 2214, 2186,  886, 2167, 1180, 2214,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0],
        [ 912, 2186,  354, 1443,  810,  821,  354,  410,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0],
        [ 747, 1762, 1818, 1439, 1563, 1973,  196,  991,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0]]) tensor([[   2,  537,    3,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0],
        [   2,  426,    3,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0],
        [   2, 1970,  421,    3,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0],
        [   2, 1374,    3,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0]])
tensor([[ 607, 2186,  354,  669,  110, 1692,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0],
        [ 747, 1762,  170, 1801, 2154,  821,   56, 1186,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0],
        [ 446, 2186,  532,  821,  912, 1469,  110,  354, 1866,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0],
        [ 354, 1708, 2186, 1494, 1773,  354,    5,  136,  912,  879,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0]]) tensor([[   2, 1569, 2024,    3,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0],
        [   2, 1329,    3,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0],
        [   2,  303,  677,    3,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0],
        [   2,  503,    3,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0]])
tensor([[ 912, 1453,  786,  632, 2237, 2269,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0],
        [ 410,  917,  985, 2186, 1966, 2269,  672,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0],
        [ 912, 2186,  354,  953, 1207,  636,  821,  807,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0],
        [ 747, 1762,  269, 2186,   56,  265,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0]]) tensor([[   2, 1708,    3,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0],
        [   2,  598, 1349,    3,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0],
        [   2, 1104,  636,  894,    3,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0],
        [   2,  992,    3,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0]])
tensor([[ 912,   94,  683, 1015,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0],
        [1508,  110, 1308,  384, 1596, 1009, 1661, 2268,  110, 1080, 2186,  886,
         2167,  275,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0],
        [1117,  354, 1581, 2173,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0],
        [1453, 1708, 2186, 1536,  608,   56, 1995,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0]]) tensor([[   2,  407,    3,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0],
        [   2, 2069,    3,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0],
        [   2,  721, 1138,    3,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0],
        [   2, 1153,    3,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0]])
tensor([[ 396, 2186,  886, 2167,  354, 1573,  110, 1669,  400,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0],
        [ 821,  912, 1127,  893, 1961, 1878,  354, 1069, 1304,  410,  402,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0],
        [  47, 1495,  653, 1302,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0],
        [ 821,  912, 1120, 2186,  354, 1822,  953, 1156,  532,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0]]) tensor([[   2,  295,  715,    3,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0],
        [   2, 2070,    3,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0],
        [   2, 1302,    3,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0],
        [   2, 1670,    3,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0]])
tensor([[ 354, 1264,   69, 2283,  354,    5,   87,  354, 1708, 2186, 1677,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0],
        [ 459,  354,  985,  384,  898,  625,  346,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0],
        [ 912, 1679, 1285,  128, 2109, 1252,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0],
        [ 607, 2186,  354, 1936,  110,  332,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0]]) tensor([[   2, 1410, 1059, 2111,    3,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0],
        [   2,  546,    3,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0],
        [   2,  428,  220,   87, 1850,    3,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0],
        [   2, 2027,    3,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0]])
tensor([[ 607, 2186,  354,   90,  187,  110,  354,  153,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0],
        [2154, 1801,  790, 2240,  821, 1523,  943, 2133,  781, 1565, 1359,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0],
        [  56,  589, 1452, 2186,  573,   56,  639,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0],
        [ 396,  806,  354,  413, 1270,  236,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0]]) tensor([[   2,  153, 2186, 1479,    3,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0],
        [   2, 1359, 1523,  943,  577,  560,  795, 2192, 1953, 1921, 2186,   56,
         1791, 1453,    3,    0,    0,    0,    0,    0,    0],
        [   2, 1631,    3,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0],
        [   2, 1286, 2147,    3,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0]])
tensor([[ 747, 1762,  907, 1439,   56, 2099,  991,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0],
        [1960, 2060, 1997,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0],
        [ 812,  690, 1801,  750, 2081, 1401,   92,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0],
        [2308,  560, 1473,  765,  821,   56, 1047,   27,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0]]) tensor([[   2,  827,    3,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0],
        [   2,  410, 1026, 1121,    3,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0],
        [   2,  817,    3,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0],
        [   2,  783,    3,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0]])
tensor([[ 607, 2186,  354, 1211,  110,  633,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0],
        [  56,  853, 2239, 1335,  110,  747, 1762, 1421,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0],
        [ 912, 2186,  354, 1236, 2214,  821,  354,  410,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0],
        [ 396,  683,  354,  191, 1725,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0]]) tensor([[   2, 2079,    3,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0],
        [   2, 1246,    3,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0],
        [   2, 1641,    3,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0],
        [   2, 1662,    3,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0]])
tensor([[ 912, 1422, 2186,  886, 2167, 1916,  110,  491,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0],
        [ 149,  674, 1579,  819,  275,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0],
        [ 396, 2186, 2095,  886, 2167,  354, 1824,  110, 1961,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0],
        [ 912, 2186,  354,  451,  568,  821,  354,  410,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0]]) tensor([[   2, 1710, 1532,    3,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0],
        [   2,  206,    3,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0],
        [   2, 1697,    3,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0],
        [   2,  388,  568,    3,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0]])
tensor([[ 187,  110, 2297, 2186,  639,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0],
        [ 747, 1762,  765, 1801, 2154,  821,   56, 1127,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0],
        [1197, 2186,  354,  416,  110,  912, 1614,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0],
        [ 489, 1285, 2170,  161,  597,  781, 1565, 1359,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0]]) tensor([[   2, 1480,    3,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0],
        [   2, 1690,    3,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0],
        [   2, 1614, 1552,    3,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0],
        [   2,  781, 1285,  608, 1272, 1615,   87, 1648, 2170,  161, 1815,  596,
          354, 1060,  110,  839, 2195,   87, 2201, 1585,    3]])
tensor([[1388, 2186,  157, 1096,  639,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0],
        [ 607, 2186,   56,  994, 1009,  827,  412, 1340,  573,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0],
        [ 396, 2186,  354, 1069, 2294, 1773, 1542, 1773,  439,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0],
        [ 354, 1609,  110, 1432, 1801,  157,  110,   88,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0]]) tensor([[   2, 1252,    3,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0],
        [   2, 1254,  994,    3,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0],
        [   2,  957,  909,    3,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0],
        [   2,  523,    3,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0]])
tensor([[ 912, 2186,  354,  451, 2214,   56,  807, 1551,  426, 1669, 1641, 1552,
          761,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0],
        [ 507,  786,  513, 1542,  200,  513, 1801, 1174,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0],
        [ 396,   25,  354, 1069, 1807, 1773,  239,  354, 2274,  110, 1227,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0],
        [ 912, 2186,  354,  101, 1689,  110,  354,  606,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0]]) tensor([[   2,   37,  807,    3,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0],
        [   2, 1813,    3,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0],
        [   2,   12,    3,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0],
        [   2, 1187,    3,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0]])
tensor([[ 912, 2186,  354,  953, 1422,  821,  354,  410,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0],
        [ 396,  683,  870, 1282,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0],
        [ 856,  162, 1049,  338, 1773,   88,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0],
        [ 200,  893,  354, 1890, 1130,    9, 1237,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0]]) tensor([[   2, 2249,  776,    3,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0],
        [   2,  343,  928,    3,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0],
        [   2, 1324,    3,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0],
        [   2, 1238, 1241, 2070,    3,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0]])
tensor([[ 607, 2186,  354, 1755,  110,   56, 2196,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0],
        [2252, 1720, 2186, 1862, 1773,  813,  275,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0],
        [ 747, 1762,   77, 1801, 2154,  821,   56, 1304, 2239,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0],
        [ 396,  806,  354, 1962, 1021, 1784,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0]]) tensor([[   2,   56, 2196,   53, 1174,   13,    3,    0,    0,    0,    0,    0,

In [332]:
print(q.shape,a.shape)

torch.Size([2, 28]) torch.Size([2, 21])

In [333]:
class encoder(nn.Module):
    def __init__(self, vocab_size, embed_dim, hidden_dim):
        super().__init__()
        self.embedding = nn.Embedding(
        vocab_size, 
        embed_dim,
        padding_idx = 0
        )
        self.gru = nn.GRU(
        embed_dim,
        hidden_dim,
        batch_first = True
        )

    def forward(self, x):
        embed = self.embedding(x)
        outputs, hidden = self.gru(embed)
        return hidden

In [334]:
class decoder(nn.Module):
    def __init__(self, vocab_size, embed_dim, hidden_dim):
        super().__init__()
        self.embedding = nn.Embedding(
        vocab_size,
        embed_dim,
        padding_idx = 0
        )
        self.gru = nn.GRU(
        embed_dim,
        hidden_dim,
        batch_first = True
        )
        self.classif = nn.Linear(
        hidden_dim,
        vocab_size
        )

    def forward(self, tok, hid):
        embed = self.embedding(tok)
        output, hid = self.gru(embed, hid)
        logits = self.classif(output)
        return logits, hid

In [335]:
class seq2seq(nn.Module):
    def __init__(self, encoder, decoder):
        super().__init__()
        self.encoder = encoder
        self.decoder = decoder

    def forward(self, q, a):
        hid = self.encoder(q)
        decoder_input = a[:, :-1]
        logits, _ = self.decoder(decoder_input, hid)

        return logits

In [336]:
encoder = encoder(
    vocab_size = len(vocabulary),
    embed_dim = 64,
    hidden_dim = 128,
)

decoder = decoder(
    vocab_size = len(vocabulary),
    embed_dim = 64,
    hidden_dim = 128,
)

model = seq2seq(
    encoder,
    decoder
)

In [346]:
crit = nn.CrossEntropyLoss(ignore_index = 0)
lr = 0.01
epochs = 100

In [347]:
optimizer = torch.optim.Adam(model.parameters(), lr = lr)

In [348]:
for epoch in range(epochs):
    tot_loss = 0
    for q, a in train_load:
        logits = model(q, a)
        targets = a[:, 1:]
        loss = crit(logits.reshape(-1, logits.shape[-1]), targets.reshape(-1))
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        tot_loss += loss.item()

    avg_loss = (tot_loss / len(train_load))
    print(f'epoch: {epoch} loss: {avg_loss}')

epoch: 0 loss: 3.58513653433438
epoch: 1 loss: 3.3348935462495457
epoch: 2 loss: 3.389253042302546
epoch: 3 loss: 3.526460331319052
epoch: 4 loss: 3.584263842568889
epoch: 5 loss: 3.4288249539437228
epoch: 6 loss: 3.542771111806063
epoch: 7 loss: 3.656615276753007
epoch: 8 loss: 3.7056174440381353
epoch: 9 loss: 3.5708072502725625
epoch: 10 loss: 3.7108250235333786
epoch: 11 loss: 3.313891154374176
epoch: 12 loss: 3.0970142626772184
epoch: 13 loss: 3.297169406620522
epoch: 14 loss: 3.270278858663934
epoch: 15 loss: 3.1556495500992296
epoch: 16 loss: 3.1198863980156477
epoch: 17 loss: 2.810615798224627
epoch: 18 loss: 2.851580840252543
epoch: 19 loss: 2.513874232864943
epoch: 20 loss: 2.6921675219709558
epoch: 21 loss: 2.679347505524171
epoch: 22 loss: 2.5324637784418758
epoch: 23 loss: 2.6009889723405304
epoch: 24 loss: 2.7574163412899098
epoch: 25 loss: 2.951385712730718
epoch: 26 loss: 2.49155044536528
epoch: 27 loss: 2.2284132879978853
epoch: 28 loss: 2.2572194597095026
epoch: 29 loss: 2.3424877507855433
epoch: 30 loss: 2.051472323173717
epoch: 31 loss: 2.380705643653102
epoch: 32 loss: 2.2011653380457714
epoch: 33 loss: 2.282151873437453
epoch: 34 loss: 2.5956562141296837
epoch: 35 loss: 2.521520871745561
epoch: 36 loss: 2.197877095542576
epoch: 37 loss: 2.2686525928036434
epoch: 38 loss: 2.371095166043998
epoch: 39 loss: 2.498242948621975
epoch: 40 loss: 2.301883587069098
epoch: 41 loss: 2.444709495828405
epoch: 42 loss: 2.3677375930738176
epoch: 43 loss: 2.2798844712968025
epoch: 44 loss: 2.3116344062905245
epoch: 45 loss: 2.1806370744775467
epoch: 46 loss: 1.9936334030720697
epoch: 47 loss: 2.1902107817951246
epoch: 48 loss: 2.1277706548523985
epoch: 49 loss: 2.340573202508551
epoch: 50 loss: 2.2909622758790817
epoch: 51 loss: 2.2417254008684884
epoch: 52 loss: 2.4320077174732884
epoch: 53 loss: 2.330857578808913
epoch: 54 loss: 2.311470388264451
epoch: 55 loss: 2.334373747122518
epoch: 56 loss: 2.2203553345113347
epoch: 57 loss: 2.318499920064835
epoch: 58 loss: 2.266119973813963
epoch: 59 loss: 2.097120611484851
epoch: 60 loss: 1.686280411323066
epoch: 61 loss: 1.7180007398838735
epoch: 62 loss: 1.902618160463045
epoch: 63 loss: 2.327012684513909
epoch: 64 loss: 2.408355984964724
epoch: 65 loss: 2.1210287136154036
epoch: 66 loss: 2.1901138208871016
epoch: 67 loss: 1.8574545835727208
epoch: 68 loss: 1.8986051405581654
epoch: 69 loss: 1.9931679562810152
epoch: 70 loss: 2.053629495386737
epoch: 71 loss: 1.772500364350636
epoch: 72 loss: 1.7877927611986624
epoch: 73 loss: 2.0036084048877556
epoch: 74 loss: 1.9916149600680773
epoch: 75 loss: 1.9873230944724183
epoch: 76 loss: 2.093034815316325
epoch: 77 loss: 1.911073919296018
epoch: 78 loss: 2.0525212181453387
epoch: 79 loss: 1.9815163388399257
epoch: 80 loss: 1.8037102950162283
epoch: 81 loss: 1.8893139055215942
epoch: 82 loss: 2.060268744299898
epoch: 83 loss: 1.9419741405155435
epoch: 84 loss: 2.0664462075950443
epoch: 85 loss: 2.0306507893118337
epoch: 86 loss: 2.3153282602118126
epoch: 87 loss: 2.6332348639058227
epoch: 88 loss: 2.6341900224241583
epoch: 89 loss: 2.5917266433126227
epoch: 90 loss: 2.3625532341447277
epoch: 91 loss: 2.261508814760301
epoch: 92 loss: 2.1471371232608973
epoch: 93 loss: 2.0855026918842134
epoch: 94 loss: 2.13512135156718
epoch: 95 loss: 2.1247481895838525
epoch: 96 loss: 2.261725433465956
epoch: 97 loss: 2.305004847923462
epoch: 98 loss: 2.082491579555604
epoch: 99 loss: 2.115327981886757

In [349]:
torch.save(model.state_dict(), 'rnn_qa.pth')

In [351]:
idx_to_word = {v:k for k,v in vocabulary.items()}

In [378]:
def generate(model, question_tensor, SOS, EOS, idx_to_word, max_len = 20):

    model.eval()
    with torch.no_grad():

        if question_tensor.dim() == 1:
            question_tensor = question_tensor.unsqueeze(0)

        hidden = model.encoder(question_tensor)
        token = torch.tensor([[SOS]], dtype = torch.long, device = question_tensor.device)

        generated_tokens = []
        for _ in range(max_len):
            logits, hidden = model.decoder(token, hidden)
            token = logits.argmax(dim = -1)
            predicted_id = token.item()

            if predicted_id == EOS:
                break

            generated_tokens.append(predicted_id)

        words = [idx_to_word[i] for i in generated_tokens]
        return " ".join(words)

In [379]:
q, a = dataset[0]
generate(model, q, 2, 3, idx_to_word)

'seven'

In [380]:
for i in q:
    print (idx_to_word[int(i)])

how
many
days
do
we
have
in
a
week
<PAD>
<PAD>
<PAD>
<PAD>
<PAD>
<PAD>
<PAD>
<PAD>
<PAD>
<PAD>
<PAD>
<PAD>
<PAD>
<PAD>
<PAD>
<PAD>
<PAD>
<PAD>
<PAD>